dist: xenial

language: python

# https://github.com/neovim/bot-ci#generated-builds
before_install:
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

python:
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt -r requirements-test.txt

script:
  - pytest
